### ISSUE TITLE
Features Suggestions

### ISSUE THREAD

**Issue by kostasx** [nickaiva/worldcities#1]
- It would be nice to update the DETAILS PANEL when the users have selected a different country. Now, when I select Albania, pick a city and then select Italy, the DETAILS PANEL keeps showing Albania. I have to pick a city in order for the DETAILS PANEL to be updated.
- It would be nice to use the datalist input element so that the users are able to write part of the country name and see a list of suggestions.
- It's pretty difficult to see the letters on top of the earth image. Consider some sort of transparent background in order for the text to be readable. Also, pick a larger font because the teacher is getting older ;)
- Make sure the users are able to pan and zoom in the map that gets displayed
- Cache jQuery selectors when you use them more than once, e.g.

$('#details').empty()
$('#details').append();

const $details = $('#details');

$details.empty();
$details.append();

This way, jQuery $() won't have to traverse the document everytime you call the function but will instead use the cached version stored in the variable (much, much faster).
- Prefer template literals for Strings that span multiple lines instead of string + concatenation
- Avoid inline event handlers, e.g. onchange and prefer addEventListener("change", ... )

**Comment by nickaiva** [comment]
With the exception of datalist use, most of the suggestions more or less followed
